# Generated by Django 5.1.4 on 2025-01-31 05:16

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=244)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField()),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10), size=None)),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'SENT'), ('awaiting', 'AWAITING')], max_length=9)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.DateTimeField(default=django.utils.timezone.now)),
                ('classy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vip', 'VIP'), ('rep', 'REP'), ('std', 'STD')], max_length=3)),
                ('notes', models.CharField(blank=True, choices=[('faltou', 'FALTOU'), ('esqueceu', 'ESQUECEU'), ('atestado', 'ATESTADO')], max_length=9, null=True)),
                ('expected', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), max_length=2, size=None)),
                ('register', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, null=True), blank=True, max_length=2, null=True, size=None)),
                ('classy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
