# Generated by Django 5.1.4 on 2025-02-10 14:11

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_range', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_range', models.DateTimeField()),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]), size=None)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField()),
                ('p256dh', models.CharField(max_length=256)),
                ('auth', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.JSONField(default=dict)),
                ('reviewed', models.BooleanField(default=False)),
                ('to_review', models.BooleanField(default=False)),
                ('end', models.DateTimeField()),
                ('start', models.DateTimeField()),
                ('absences', models.IntegerField()),
                ('total_minutes', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vip', 'VIP'), ('rep', 'REP'), ('std', 'STD')], max_length=3)),
                ('notes', models.CharField(blank=True, choices=[('faltou', 'FALTOU'), ('esqueceu', 'ESQUECEU'), ('atestado', 'ATESTADO')], max_length=9, null=True)),
                ('expected', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), max_length=2, size=None)),
                ('register', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, max_length=2, null=True, size=None)),
                ('classy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.class')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
