# Generated by Django 5.1.4 on 2025-02-04 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='register',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, max_length=2, null=True, size=None),
        ),
    ]
